server {
    listen 80;
    root /var/www/public;

    client_max_body_size 80M;

    location /api {
        proxy_pass http://api:3000;
    }

    location /uploads {
        proxy_pass http://api:3000;
    }

    location / {
        proxy_pass http://dashboard:3001;
    }
}
